apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: example-wag
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: default-europe-west1
    spec:
      serviceAccountName: wag-example-sa@my-project.iam.gserviceaccount.com
      containers:
      - env:
        - name: WAG_USE_CONFIG
          value: '1'
        - name: WAG_DEBUG
          value: '1'
        - name: WAG_BUCKET_NAME
          value: 'my-project-example-media'
        - name: WAG_ENGINE
          value: 'django.db.backends.postgresql_psycopg2'
        - name: WAG_NAME
          value: 'cmsdb'
        - name: WAG_USER
          value: 'cmsuser'
        - name: WAG_HOST
          value: '10.9.212.5'
        - name: WAG_PORT
          value: '5432'
        - name: WAG_APP_NAME
          value: 'example'
        - name: ENABLE_MANAGE_ENDPOINT
          value: '1'
        - name: _INDEX
          value: '1'
        image: gcr.io/my-project/example-image:latest
        volumeMounts:
        - mountPath: /appvar
          name: APPLICATION_SECRETS_VOL
      volumes:
      - name: APPLICATION_SECRETS_VOL
        secret:
          items:
          - key: latest
            path: .env
          secretName: wag-example

